[rules]
include = ["~*"]

[settings]
include = ["~*", "#maximum-privacy/*", "#read-only/*"]

[skills]
include = ["~*", "#troubleshooting/*", "#aliases/*", "#design/*"]

[templates]
include = ["~*"]

[workflows]
include = ["~*"]
