[rules]
include = ['~*', '#golang/*', '#ci/*', '#quality/*']

[commands]
include = ['~*', '#golang/*', '#ci/*', '#quality/*']

[templates]
include = ['~*', '#golang/*', '#ci/*', '#quality/*']

[workflows]
include = ['~*', '#golang/*', '#ci/*', '#quality/*']
